version: "3"
services:
  task_template:
    build:
      context: ./task_template
      dockerfile: Dockerfile_openai
    ports:
      - 0.0.0.0:8070:8061
      - 8062:8062
    networks:
      - mynetwork
  model_template:
    build: ./model_template
    ports:
      - 0.0.0.0:8072:8061
    networks:
      - mynetwork
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  model_handler_template:
    build: ./model_handler_template
    ports:
      - 0.0.0.0:8071:8061
    networks:
      - mynetwork
    environment:
      - USE_ATLAS=False
      - ATLAS_URI=${ATLAS_URI}
  orchestrator:
    depends_on:
      - task_template
      - model_template
      - model_handler_template
    build: ./orchestrator
    networks:
      - mynetwork
  nginx:
    image: docker.io/library/nginx:alpine
    environment:
      - NGINX_HTTPS_PORT=443
      - HOSTNAME=localhost
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./dev_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dev_data/nginx/templates:/etc/nginx/templates
      - ./dev_data/certs/sp.crt:/certificates/certificate.crt
      - ./dev_data/certs/sp.key:/certificates/private.key
    depends_on:
      - task_template
    container_name: nginx-server
    networks:
      - mynetwork
networks:
  mynetwork:
