FROM node:22.13.0 AS frontend-builder

WORKDIR /frontend
COPY ./frontend_code_tutor ./
RUN npm install
RUN npm audit fix
RUN npm run build


# Dockerfile
FROM python:3.12
WORKDIR /usr/project

ARG UV_COMPILE_BYTECODE=1
ARG EXPECTED_UV_SHA256=76c856787708ae47b7e776daf7ad61a83e43e50c895537aacffc24da90ab55a4
ARG EXPECTED_UVX_SHA256=020a0266a73de991d2ddd6c009bd1178222affce05918d4eabe73e4ab2df741c

# UV specific environment
ENV UV_LINK_MODE="copy"
# Enable bytecode compilation for production
ENV UV_COMPILE_BYTECODE=${UV_COMPILE_BYTECODE}
ENV UV_PROJECT_ENVIRONMENT=/usr/local/venv


ARG USERNAME=appuser

# Install base dependencies
RUN apt-get update && apt-get install -y libffi-dev

# Create user to run the server with
RUN useradd -ms /bin/bash $USERNAME

# Install UV from their official image
COPY --from=ghcr.io/astral-sh/uv:0.9.16 /uv /uvx /usr/local/bin/
RUN echo "${EXPECTED_UV_SHA256}  /usr/local/bin/uv" | sha256sum -c - && \
    echo "${EXPECTED_UVX_SHA256}  /usr/local/bin/uvx" | sha256sum -c -

WORKDIR /app

# Copy environment creation files
COPY pyproject.toml ./pyproject.toml
COPY uv.lock ./uv.lock

# Install python dependencies
RUN uv sync --frozen --no-dev  

# Add venv bin to PATH
ENV PATH="/usr/local/venv/bin:$PATH"

COPY app ./app
COPY run.sh ./run.sh
COPY --from=frontend-builder /frontend/dist ./dist

USER $USERNAME

# Set env variables
ENV OPENAI_API_KEY="PROVIDE_EXERNALLY"
ENV TASK_NAME code_tutor

CMD ["./run.sh"]