// const TaskDescription = () => {
//   return (
//     <div className="task-description">
//       <h2>🖋️ Chrono-Cross StoryWeaver</h2>
//       <div className="systemlogo-section">
//         <img src="./storyteller.png" alt="System Logo" />
//       </div>

//       <div className="user-guide-section">
//         <h3>📜 User Guide</h3>
//         <ol>
//           <li>The user choose a theme for the story. The theme could be writen in any language. After that, the first line is generated by the AI</li>
//           <li>The user and AI take turns to write the story</li>
//           <li>There are two input field: the first one is for adding a new storyline, the second one is for sending the model a comment</li>
//           <li>The story is finished when it reaches the 9-line limit</li>
//         </ol> 
//       </div>
//     </div>
//   );
// };

// export default TaskDescription;

// const TaskDescription = () => {
//   return (
//     <div className="task-description">
//       <h2 className="center-text">🖋️ Chrono-Cross StoryWeaver</h2>
//       <div className="content-section">
//         <div className="systemlogo-section">
//           <img src="./storyteller.png" alt="System Logo" />
//         </div>
//         <div className="user-guide-section">
//           <h3>📜 User Guide</h3>
//           <ol>
//             <li>The user choose a theme for the story. The theme could be writen in any language. After that, the first line is generated by the AI</li>
//             <li>The user and AI take turns to write the story</li>
//             <li>There are two input field: the first one is for adding a new storyline, the second one is for sending the model a comment</li>
//             <li>The story is finished when it reaches the 9-line limit</li>
//           </ol>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default TaskDescription;



const TaskDescription = () => {
  return (
    <div className="task-container">
      {/* <h2 className="center-header">Have a try!!</h2> */}
      <div className="content-section">
        <div className="systemlogo-section">
          <img src="./storyteller.png" alt="System Logo" />
        </div>
        <div className="user-guide-section">
          <h3>📜 User Guide</h3>
          <ol>
            <li>The user choose a theme for the story. The theme could be writen in ANY language. After that, the first line is generated by the AI</li>
            <li>The user and AI take turns to write the story</li>
            <li>There are two input field: the first one is for adding a new storyline, the second one is for sending the model a comment</li>
            <li>The new storyline written by user should be in English, the comment to the model could be in ANY language!</li>
            <li>The story is finished when it reaches the 9-line limit</li>
          </ol>
        </div>
      </div>
    </div>
  );
};

export default TaskDescription;
