const TaskDescription = () => {
  return (
    <div className="task-description">
      <h2>🖋️ Poetry task</h2>
      <h3>📜 Rules</h3>
      <ol>
        <li>The user choose a theme for the poem. After that, the first line is generated by the AI</li>
        <li>The user and AI take turns to write the poem</li>
        <li>To write a poem line, please wrap your poem line inside square brackets. Anything outside of that will be treated as a message to the model and won't be rendered in the dialogue section</li>
        <li>The poem is finished when it reaches the 9-line limit</li>
      </ol>
    </div>
  );
};

export default TaskDescription;
